# Monitoramento de animais silvestre
#   Criado por:
# 		-Andre Roberti Ra:08
# 		-Henrique Gonzales Ra:083636
# 		-Tiago Chedraoui Silva Ra:082941

CC = gcc
CFLAGS = -g -W -Wall -std=gnu99
LIBS = -lm

OBJS = main.c

all: 
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) -o lab1
	
test:
	./lab1	

clean:
	rm -f lab1
